#!/bin/bash

get_dns_info() {
    local domain=$1
    local subdomain=$2

    dig_output=$(dig ${subdomain}.${domain} | awk '/ANSWER SECTION:/,0')

    if [[ -n $dig_output ]]; then
        record_type=$(echo "$dig_output" | awk '{print $4}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
    else
        echo "No information found for subdomain ${subdomain}"
    fi
}

domain=$1
subdomain=$2

if [[ -z $subdomain ]]; then
    get_dns_info $domain www
    get_dns_info $domain lb-01
    get_dns_info $domain web-01
    get_dns_info $domain web-02
else
    get_dns_info $domain $subdomain
fi
