#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Modify Nginx configuration for custom 404 page
sudo sed -i '/listen \[::\]:80 default_server;/a \    error_page 404 /404.html;' /etc/nginx/sites-enabled/new_config
sudo sed -i '/listen \[::\]:80 default_server;/a \    location = /404.html {\n        root /var/www/html;\n        internal;\n    }' /etc/nginx/sites-enabled/new_config

# Restart Nginx to apply changes
sudo service nginx restart

