#!/usr/bin/env bash
# shellcheck disable=SC2154
# installs haproxy on a new load balancer and setups the config
# apt-get -y update
# apt-get -y install haproxy
# echo "ENABLED=1" | tee -a /etc/default/haproxy
# mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
# echo -e "defaults\n\tmode http\n\ttimeout connect 5000\n\ttimeout client 10000\n\ttimeout server 10000\n\ttimeout http-request 100\n\nfrontend myfrontend\n\tbind :80\n\tdefault_backend myservers\n\nbackend myservers\n\tserver 182159-web-01 18.234.106.179\n\tserver 182159-web-02 34.207.83.122" | tee /etc/haproxy/haproxy.cfg
#service haproxy restart

# Install Nginx
# apt-get update
# apt-get install -y nginx

# Configure Nginx to listen on port 80
# sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default

# Restart Nginx
#service nginx restart

# Second solution
# debugging nginx port 80
# How I solved it: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link.
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
